language: node_js
addons:
  chrome: stable
before_install:
  - npm install -g @lhci/cli@0.3.x
script:
  - npm install
after_success:
  - lhci autorun --upload.target=temporary-public-storage
