language: node_js
node_js:
  - lts/*
addons:
  chrome: stable
script:
  - yarn build
  - lhci autorun
after_success:
  - lhci upload
deploy:
  provider: pages
  local_dir: ./dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
